aws_profile       = "personal"
aws_region        = "us-east-1"
db_instance_class = "db.t1.micro"
dbname            = "mydb"
dbuser            = ""
dbpassword        = ""
key_name          = "terraform"
public_key_path   = "root/.ssh/terraform.pub"
